<#if onclick!=""> onclick="${onclick}"</#if><#rt/>
<#if ondblclick!=""> ondblclick="${ondblclick}"</#if><#rt/>
<#if onmousedown!=""> onmousedown="${onmousedown}"</#if><#rt/>
<#if onmouseup!=""> onmouseup="${onmouseup}"</#if><#rt/>
<#if onmouseover!=""> onmouseover="${onmouseover}"</#if><#rt/>
<#if onmousemove!=""> onmousemove="${onmousemove}"</#if><#rt/>
<#if onmouseout!=""> onmouseout="${onmouseout}"</#if><#rt/>
<#if onfocus!=""> onfocus="${onfocus}"</#if><#rt/>
<#if onblur!=""> onblur="${onblur}"</#if><#rt/>
<#if onkeypress!=""> onkeypress="${onkeypress}"</#if><#rt/>
<#if onkeydown!=""> onkeydown="${onkeydown}"</#if><#rt/>
<#if onkeyup!=""> onkeyup="${onkeyup}"</#if><#rt/>
<#if onselect!=""> onselect="${onselect}"</#if><#rt/>
<#if onchange!=""> onchange="${onchange}"</#if><#rt/>