

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: nutzbook
  volumes:
    - /var/lib/mysql
  command : "mysqld --character-set-server=utf8"
redis:
  image: redis
web:
  image: wendal/nutzbook
  links:
    - db
    - redis
  environment:
    "NUTZBOOK_db.url" : "jdbc:mysql://db/nutzbook"
    "NUTZBOOK_redis.host" : "redis"
    "OAUTH_api.github.com.consumer_key" : ""
    "OAUTH_api.github.com.consumer_secret" : ""
    "OAUTH_api.github.com.custom_permissions" : "user:email"

    "NGROK_auth_token" : ""
    "NGROK_server_addr" : "wendal.cn:4443"
    "NGROK_trust_host_root_certs" : "true"
  ports:
    - "8080:8080"
    - "81:81"
  volumes:
    - "/dev/urandom:/dev/random"
